#
# SPDX-FileCopyrightText: 2021 George Florea Bănuș <georgefb899@gmail.com>
#
# SPDX-License-Identifier: CC-BY-4.0
#
github: g-fb
liberapay: gfb
patreon: georgefb
custom: "https://www.paypal.me/georgefloreabanus"
